import type { Metadata } from "next";

import { inter } from "@/app/ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " bg-blue-600 min-h-screen h-screen p-2"}
      >
        <main className="border-2 border-white rounded-lg h-full w-full p-1">
          {children}
        </main>
      </body>
    </html>
  );
}
